### ISSUE TITLE
Select VPS Provider

### ISSUE THREAD

**Issue by aeturnum** [health-environment-ethnography-lab/pheel_info#1]
Spreadsheet of possible VPS providers: https://drive.google.com/open?id=1avDv7W1r0Rg6DBZGGy8s7nPVlayu4vSUwSQKPNrzKcA

VPS recommendation report: https://drive.google.com/open?id=1wsp_gLkPf1r6H6JmaXQYeY1XMZEDNoDkCjZ9ba_CWOI

(note links are read only because this issue is public - please message me for write links if needed)

**Comment by akenner** [comment]
Didn't we decide this? Or are you waiting for my ultimate go ahead? Let's discuss Brian's comment on Friday. But I think that Inmotion option is our winner... Am I going to need my credit card on Friday?

**Comment by aeturnum** [comment]
It doesn't have to be friday - but we do need to sign up with a provider before we can begin the work. :)

**Comment by akenner** [comment]
I have approval and the plastic to make this purchase. Tomorrow before class?

**Comment by aeturnum** [comment]
I think we're ready. I'll be around the office.
