### ISSUE TITLE
EEA Urban Outlines

### ISSUE THREAD

**Issue by akenner** [health-environment-ethnography-lab/pheel_info#10]
We are having a problem with one of the layers on Maps Marker Pro and got this response from their tech support: 

> Hi Alison,
> EEA - Urban Outlines is/was provided by discomap EU service - it seems it is no
> longer available, at least I could not find any related configuration info for
> that layer on https://discomap.eea.europa.eu/Index/
> best,
> Lisa

I'm wondering if there is an alternative way to do such outlines in MMP...

**Comment by aeturnum** [comment]
@akenner Could you explain what the overlay did? I'm not familiar with the system.

**Comment by aeturnum** [comment]
It seems like this USGS page might be helpful (the "structures" selection under Theme Overlays), but after adding it to the map plugin it doesn't seem to work. I'll keep looking.

**Comment by akenner** [comment]
I think we'll have to ask Skylar what kind of functionality she was looking for. This is her gig. We should maybe get her on this GitHub kick too...

**Comment by aeturnum** [comment]
Absolutely! FWIW, I suspect that I'm simply mis-configuring this USGS map. If we figure out what we want the best approach is probably to ask the Maps Maker Pro people for the correct settings to use the USGS map overlay.

**Comment by akenner** [comment]
That sounds really good. I'll add this to the agenda for Skylar and I next week.

**Comment by akenner** [comment]
The latest from the MMP team:

> Unfortunately I do not know any - anyway our plugin offers to connect to all
> kinds of wtms services, so if you find a wmts service from an external provider
> which supports what you need, so that you can use it in our plugin... 
> best, 
> Lisa

**Comment by aeturnum** [comment]
US Census also provides maps: https://tigerweb.geo.census.gov/tigerwebmain/tigerweb_restmapservice.html

**Comment by akenner** [comment]
Is this something that you could plug into the website for us? How does it work? This is perfect... Good find!

**Comment by aeturnum** [comment]
Oops - I thought I had posted this, but I guess I didn't: https://viewer.nationalmap.gov/services/

@akenner I had tried to plug in the above link, but I couldn't get it to work. I can keep working at it. I'll see if I can figure out how to fix it.

**Comment by akenner** [comment]
OK thanks Drex. I think the main thing we're looking for is census data overlays, but @jskylarricci correct me if I'm wrong.
Also - we'll be having a casual work session from 11:30-1:30 today at 3101...

**Comment by aeturnum** [comment]
Recording to save time for the future:
Simple reference on the protocol: https://geoserver.geo-solutions.it/edu/en/pretty_maps/wms.html
More reference: https://docs.geoserver.org/stable/en/user/services/wms/reference.html

To get service information:
`http -v https://tigerweb.geo.census.gov/arcgis/services/TIGERweb/tigerWMS_Current/MapServer/WMSServer \
	service==WMS \
	request==GetCapabilities \
	version==1.3.0 \`

Sample httpie request:
`http -v https://tigerweb.geo.census.gov/arcgis/services/TIGERweb/tigerWMS_Current/MapServer/WMSServer \
	service==WMS \
	version==1.3.0 \
	request==GetMap \
	layers=="Census Tracts" \
	styles== \
	format==image/png \
	transparent== \
	errorTiles==true \
	edgeBufferTiles==2 \
	width==512 \
	height==512 \
	crs==EPSG:3857 \
	 bbox==-8360376.4057194395,4862617.991389773,-8355484.435909188,4867509.961200024`

**Comment by aeturnum** [comment]
There's now a Census Tract Layer on Map Marker Pro on Pheel.info
